default_window_size = [
    500.0,
    600.0,
]
auto_save = true

[popped_tabs.Inputs]
pos_x = 485.0
pos_y = 209.0
width = 368.0
height = 585.0
collapsed = false

[popped_tabs.Block1]
pos_x = 431.0
pos_y = -9.0
width = 428.0
height = 592.0
collapsed = false

[popped_tabs.Block2]
pos_x = 909.0
pos_y = -3.0
width = 443.0
height = 601.0
collapsed = false

[popped_tabs.Settings]
pos_x = 930.0
pos_y = 209.0
width = 500.0
height = 600.0
collapsed = false

[popped_tabs.Block3]
pos_x = 1350.0
pos_y = -2.0
width = 399.0
height = 605.0
collapsed = false

[popped_tabs.Macros]
pos_x = 6.0
pos_y = 209.0
width = 500.0
height = 600.0
collapsed = false
