default_window_size = [
    500.0,
    600.0,
]
auto_save = true

[popped_tabs.Settings]
pos_x = 12.0
pos_y = 479.0
width = 450.0
height = 427.0
collapsed = false

[popped_tabs.Presets]
pos_x = 13.0
pos_y = 916.0
width = 450.0
height = 562.0
collapsed = false

[popped_tabs.Midi]
pos_x = 487.0
pos_y = 628.0
width = 449.0
height = 598.0
collapsed = false

[popped_tabs.Block2]
pos_x = 909.0
pos_y = -3.0
width = 443.0
height = 601.0
collapsed = false

[popped_tabs.Block3]
pos_x = 1396.0
pos_y = 12.0
width = 425.0
height = 601.0
collapsed = false

[popped_tabs.Macros]
pos_x = 1345.0
pos_y = 645.0
width = 500.0
height = 600.0
collapsed = false

[popped_tabs.Inputs]
pos_x = 968.0
pos_y = 678.0
width = 368.0
height = 585.0
collapsed = false

[popped_tabs.Block1]
pos_x = 478.0
pos_y = 1.0
width = 428.0
height = 592.0
collapsed = false
