//! # Parameters Module
//!
//! Defines all the parameter structures for the shader pipeline.
//! These structures mirror the uniforms used in the GL3 shaders.

use glam::{Vec3, Vec4};
use serde::{Deserialize, Serialize};

pub mod preset;
pub mod of_preset_compat;

pub use preset::*;
pub use of_preset_compat::*;

/// Block 1 parameters - Channel mixing and feedback
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct Block1Params {
    // Channel 1 parameters
    pub ch1_x_displace: f32,
    pub ch1_y_displace: f32,
    pub ch1_z_displace: f32,
    pub ch1_rotate: f32,
    pub ch1_hsb_attenuate: Vec3,
    // Individual HSB components for LFO modulation
    pub ch1_hsb_attenuate_x: f32,
    pub ch1_hsb_attenuate_y: f32,
    pub ch1_hsb_attenuate_z: f32,
    pub ch1_posterize: f32,
    pub ch1_kaleidoscope_amount: f32,
    pub ch1_kaleidoscope_slice: f32,
    pub ch1_blur_amount: f32,
    pub ch1_blur_radius: f32,
    pub ch1_sharpen_amount: f32,
    pub ch1_sharpen_radius: f32,
    pub ch1_filters_boost: f32,
    
    // Channel 1 switches
    pub ch1_h_mirror: bool,
    pub ch1_v_mirror: bool,
    pub ch1_h_flip: bool,
    pub ch1_v_flip: bool,
    pub ch1_hue_invert: bool,
    pub ch1_saturation_invert: bool,
    pub ch1_bright_invert: bool,
    pub ch1_rgb_invert: bool,
    pub ch1_geo_overflow: i32, // 0=clamp, 1=wrap, 2=mirror
    pub ch1_solarize: bool,
    pub ch1_posterize_switch: bool,
    pub ch1_hd_aspect_on: bool,
    
    // Channel 2 mix and key
    pub ch2_mix_amount: f32,
    pub ch2_key_value_red: f32,
    pub ch2_key_value_green: f32,
    pub ch2_key_value_blue: f32,
    pub ch2_key_threshold: f32,
    pub ch2_key_soft: f32,
    pub ch2_mix_type: i32, // 0=lerp, 1=add, 2=diff, 3=mult, 4=dodge
    pub ch2_mix_overflow: i32,
    pub ch2_key_order: i32,
    pub ch2_key_mode: i32,
    
    // Channel 2 adjust
    pub ch2_x_displace: f32,
    pub ch2_y_displace: f32,
    pub ch2_z_displace: f32,
    pub ch2_rotate: f32,
    pub ch2_hsb_attenuate: Vec3,
    // Individual HSB components for LFO modulation
    pub ch2_hsb_attenuate_x: f32,
    pub ch2_hsb_attenuate_y: f32,
    pub ch2_hsb_attenuate_z: f32,
    pub ch2_posterize: f32,
    pub ch2_kaleidoscope_amount: f32,
    pub ch2_kaleidoscope_slice: f32,
    pub ch2_blur_amount: f32,
    pub ch2_blur_radius: f32,
    pub ch2_sharpen_amount: f32,
    pub ch2_sharpen_radius: f32,
    pub ch2_filters_boost: f32,
    
    // Channel 2 switches
    pub ch2_h_mirror: bool,
    pub ch2_v_mirror: bool,
    pub ch2_h_flip: bool,
    pub ch2_v_flip: bool,
    pub ch2_hue_invert: bool,
    pub ch2_saturation_invert: bool,
    pub ch2_bright_invert: bool,
    pub ch2_rgb_invert: bool,
    pub ch2_geo_overflow: i32,
    pub ch2_solarize: bool,
    pub ch2_posterize_switch: bool,
    pub ch2_hd_aspect_on: bool,
    
    // FB1 feedback parameters
    pub fb1_mix_amount: f32,
    pub fb1_key_value_red: f32,
    pub fb1_key_value_green: f32,
    pub fb1_key_value_blue: f32,
    pub fb1_key_threshold: f32,
    pub fb1_key_soft: f32,
    pub fb1_mix_type: i32,
    pub fb1_mix_overflow: i32,
    pub fb1_key_order: i32,
    pub fb1_key_mode: i32, // 0=off, 1=luma, 2=chroma
    
    // FB1 geometry
    pub fb1_x_displace: f32,
    pub fb1_y_displace: f32,
    pub fb1_z_displace: f32,
    pub fb1_rotate: f32,
    pub fb1_shear_matrix: Vec4,
    // Individual shear matrix components for LFO modulation (x=X stretch, y=X shear, z=Y shear, w=Y stretch)
    pub fb1_shear_matrix_x: f32,
    pub fb1_shear_matrix_y: f32,
    pub fb1_shear_matrix_z: f32,
    pub fb1_shear_matrix_w: f32,
    pub fb1_kaleidoscope_amount: f32,
    pub fb1_kaleidoscope_slice: f32,
    
    // FB1 switches
    pub fb1_h_mirror: bool,
    pub fb1_v_mirror: bool,
    pub fb1_h_flip: bool,
    pub fb1_v_flip: bool,
    pub fb1_rotate_mode: i32,
    pub fb1_geo_overflow: i32,
    
    // FB1 color
    pub fb1_hsb_offset: Vec3,
    // Individual HSB offset components for LFO modulation
    pub fb1_hsb_offset_x: f32,
    pub fb1_hsb_offset_y: f32,
    pub fb1_hsb_offset_z: f32,
    pub fb1_hsb_attenuate: Vec3,
    // Individual HSB attenuate components for LFO modulation
    pub fb1_hsb_attenuate_x: f32,
    pub fb1_hsb_attenuate_y: f32,
    pub fb1_hsb_attenuate_z: f32,
    pub fb1_hsb_powmap: Vec3,
    pub fb1_hue_shaper: f32,
    pub fb1_posterize: f32,
    pub fb1_posterize_invert: f32,
    pub fb1_posterize_switch: bool,
    pub fb1_hue_invert: bool,
    pub fb1_saturation_invert: bool,
    pub fb1_bright_invert: bool,
    
    // FB1 filters
    pub fb1_blur_amount: f32,
    pub fb1_blur_radius: f32,
    pub fb1_sharpen_amount: f32,
    pub fb1_sharpen_radius: f32,
    pub fb1_temporal_filter1_amount: f32,
    pub fb1_temporal_filter1_resonance: f32,
    pub fb1_temporal_filter2_amount: f32,
    pub fb1_temporal_filter2_resonance: f32,
    pub fb1_filters_boost: f32,
    
    // Delay time
    pub fb1_delay_time: i32,
    pub fb1_delay_time_sync: bool,
    pub fb1_delay_time_division: i32, // 0=1/16, 1=1/8, 2=1/4, 3=1/2, 4=1, 5=2, 6=4, 7=8
    
    // Input selection (0=input1, 1=input2)
    pub ch1_input_select: i32,
    pub ch2_input_select: i32,
}

/// Block 2 parameters - Secondary processing
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct Block2Params {
    // Block 2 input
    pub block2_input_x_displace: f32,
    pub block2_input_y_displace: f32,
    pub block2_input_z_displace: f32,
    pub block2_input_rotate: f32,
    pub block2_input_hsb_attenuate: Vec3,
    // Individual HSB components for LFO modulation
    pub block2_input_hsb_attenuate_x: f32,
    pub block2_input_hsb_attenuate_y: f32,
    pub block2_input_hsb_attenuate_z: f32,
    pub block2_input_posterize: f32,
    pub block2_input_kaleidoscope_amount: f32,
    pub block2_input_kaleidoscope_slice: f32,
    pub block2_input_blur_amount: f32,
    pub block2_input_blur_radius: f32,
    pub block2_input_sharpen_amount: f32,
    pub block2_input_sharpen_radius: f32,
    pub block2_input_filters_boost: f32,
    
    // Block 2 input switches
    pub block2_input_h_mirror: bool,
    pub block2_input_v_mirror: bool,
    pub block2_input_h_flip: bool,
    pub block2_input_v_flip: bool,
    pub block2_input_hue_invert: bool,
    pub block2_input_saturation_invert: bool,
    pub block2_input_bright_invert: bool,
    pub block2_input_rgb_invert: bool,
    pub block2_input_geo_overflow: i32,
    pub block2_input_solarize: bool,
    pub block2_input_posterize_switch: bool,
    pub block2_input_hd_aspect_on: bool,
    
    // FB2 feedback
    pub fb2_mix_amount: f32,
    pub fb2_key_value: Vec3,
    pub fb2_key_threshold: f32,
    pub fb2_key_soft: f32,
    pub fb2_mix_type: i32,
    pub fb2_mix_overflow: i32,
    pub fb2_key_mode: i32,
    pub fb2_key_order: i32,
    
    // FB2 geometry
    pub fb2_x_displace: f32,
    pub fb2_y_displace: f32,
    pub fb2_z_displace: f32,
    pub fb2_rotate: f32,
    pub fb2_shear_matrix: Vec4,
    // Individual shear matrix components for LFO modulation
    pub fb2_shear_matrix_x: f32,
    pub fb2_shear_matrix_y: f32,
    pub fb2_shear_matrix_z: f32,
    pub fb2_shear_matrix_w: f32,
    pub fb2_kaleidoscope_amount: f32,
    pub fb2_kaleidoscope_slice: f32,
    
    // FB2 switches
    pub fb2_h_mirror: bool,
    pub fb2_v_mirror: bool,
    pub fb2_h_flip: bool,
    pub fb2_v_flip: bool,
    pub fb2_rotate_mode: i32,
    pub fb2_geo_overflow: i32,
    
    // FB2 color
    pub fb2_hsb_offset: Vec3,
    // Individual HSB offset components for LFO modulation
    pub fb2_hsb_offset_x: f32,
    pub fb2_hsb_offset_y: f32,
    pub fb2_hsb_offset_z: f32,
    pub fb2_hsb_attenuate: Vec3,
    // Individual HSB attenuate components for LFO modulation
    pub fb2_hsb_attenuate_x: f32,
    pub fb2_hsb_attenuate_y: f32,
    pub fb2_hsb_attenuate_z: f32,
    pub fb2_hsb_powmap: Vec3,
    pub fb2_hue_shaper: f32,
    pub fb2_posterize: f32,
    pub fb2_posterize_invert: f32,
    pub fb2_posterize_switch: bool,
    pub fb2_hue_invert: bool,
    pub fb2_saturation_invert: bool,
    pub fb2_bright_invert: bool,
    pub fb2_rgb_invert: bool,
    
    // FB2 filters
    pub fb2_blur_amount: f32,
    pub fb2_blur_radius: f32,
    pub fb2_sharpen_amount: f32,
    pub fb2_sharpen_radius: f32,
    pub fb2_temporal_filter1_amount: f32,
    pub fb2_temporal_filter1_resonance: f32,
    pub fb2_temporal_filter2_amount: f32,
    pub fb2_temporal_filter2_resonance: f32,
    pub fb2_filters_boost: f32,
    
    // Delay time
    pub fb2_delay_time: i32,
    pub fb2_delay_time_sync: bool,
    pub fb2_delay_time_division: i32, // 0=1/16, 1=1/8, 2=1/4, 3=1/2, 4=1, 5=2, 6=4, 7=8
    
    // Input selection (0=block1, 1=input1, 2=input2)
    pub block2_input_select: i32,
}

/// Block 3 parameters - Final mixing and output
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct Block3Params {
    // Block 1 geo (re-processing block 1 output)
    pub block1_x_displace: f32,
    pub block1_y_displace: f32,
    pub block1_z_displace: f32,
    pub block1_rotate: f32,
    pub block1_shear_matrix: Vec4,
    // Individual shear matrix components for LFO modulation
    pub block1_shear_matrix_x: f32,
    pub block1_shear_matrix_y: f32,
    pub block1_shear_matrix_z: f32,
    pub block1_shear_matrix_w: f32,
    pub block1_kaleidoscope_amount: f32,
    pub block1_kaleidoscope_slice: f32,
    pub block1_h_mirror: bool,
    pub block1_v_mirror: bool,
    pub block1_rotate_mode: i32,
    pub block1_geo_overflow: i32,
    pub block1_h_flip: bool,
    pub block1_v_flip: bool,
    
    // Block 1 colorize
    pub block1_colorize_switch: bool,
    pub block1_colorize_hsb_rgb: i32, // 0=HSB, 1=RGB
    pub block1_colorize_band1: Vec3,
    pub block1_colorize_band1_x: f32,
    pub block1_colorize_band1_y: f32,
    pub block1_colorize_band1_z: f32,
    pub block1_colorize_band2: Vec3,
    pub block1_colorize_band2_x: f32,
    pub block1_colorize_band2_y: f32,
    pub block1_colorize_band2_z: f32,
    pub block1_colorize_band3: Vec3,
    pub block1_colorize_band3_x: f32,
    pub block1_colorize_band3_y: f32,
    pub block1_colorize_band3_z: f32,
    pub block1_colorize_band4: Vec3,
    pub block1_colorize_band4_x: f32,
    pub block1_colorize_band4_y: f32,
    pub block1_colorize_band4_z: f32,
    pub block1_colorize_band5: Vec3,
    pub block1_colorize_band5_x: f32,
    pub block1_colorize_band5_y: f32,
    pub block1_colorize_band5_z: f32,
    
    // Block 1 filters
    pub block1_blur_amount: f32,
    pub block1_blur_radius: f32,
    pub block1_sharpen_amount: f32,
    pub block1_sharpen_radius: f32,
    pub block1_filters_boost: f32,
    pub block1_dither: f32,
    pub block1_dither_switch: bool,
    pub block1_dither_type: i32, // 0=4x4, 1=8x8
    
    // Block 2 geo
    pub block2_x_displace: f32,
    pub block2_y_displace: f32,
    pub block2_z_displace: f32,
    pub block2_rotate: f32,
    pub block2_shear_matrix: Vec4,
    // Individual shear matrix components for LFO modulation
    pub block2_shear_matrix_x: f32,
    pub block2_shear_matrix_y: f32,
    pub block2_shear_matrix_z: f32,
    pub block2_shear_matrix_w: f32,
    pub block2_kaleidoscope_amount: f32,
    pub block2_kaleidoscope_slice: f32,
    pub block2_h_mirror: bool,
    pub block2_v_mirror: bool,
    pub block2_rotate_mode: i32,
    pub block2_geo_overflow: i32,
    pub block2_h_flip: bool,
    pub block2_v_flip: bool,
    
    // Block 2 colorize
    pub block2_colorize_switch: bool,
    pub block2_colorize_hsb_rgb: i32,
    pub block2_colorize_band1: Vec3,
    pub block2_colorize_band1_x: f32,
    pub block2_colorize_band1_y: f32,
    pub block2_colorize_band1_z: f32,
    pub block2_colorize_band2: Vec3,
    pub block2_colorize_band2_x: f32,
    pub block2_colorize_band2_y: f32,
    pub block2_colorize_band2_z: f32,
    pub block2_colorize_band3: Vec3,
    pub block2_colorize_band3_x: f32,
    pub block2_colorize_band3_y: f32,
    pub block2_colorize_band3_z: f32,
    pub block2_colorize_band4: Vec3,
    pub block2_colorize_band4_x: f32,
    pub block2_colorize_band4_y: f32,
    pub block2_colorize_band4_z: f32,
    pub block2_colorize_band5: Vec3,
    pub block2_colorize_band5_x: f32,
    pub block2_colorize_band5_y: f32,
    pub block2_colorize_band5_z: f32,
    
    // Block 2 filters
    pub block2_blur_amount: f32,
    pub block2_blur_radius: f32,
    pub block2_sharpen_amount: f32,
    pub block2_sharpen_radius: f32,
    pub block2_filters_boost: f32,
    pub block2_dither: f32,
    pub block2_dither_switch: bool,
    pub block2_dither_type: i32,
    
    // Matrix mixer
    pub matrix_mix_type: i32,
    pub matrix_mix_overflow: i32,
    pub bg_rgb_into_fg_red: Vec3,
    pub bg_rgb_into_fg_green: Vec3,
    pub bg_rgb_into_fg_blue: Vec3,
    // Individual matrix mixer components for LFO modulation
    // B1 Red -> B2 R/G/B
    pub matrix_mix_r_to_r: f32,
    pub matrix_mix_r_to_g: f32,
    pub matrix_mix_r_to_b: f32,
    // B1 Green -> B2 R/G/B
    pub matrix_mix_g_to_r: f32,
    pub matrix_mix_g_to_g: f32,
    pub matrix_mix_g_to_b: f32,
    // B1 Blue -> B2 R/G/B
    pub matrix_mix_b_to_r: f32,
    pub matrix_mix_b_to_g: f32,
    pub matrix_mix_b_to_b: f32,
    
    // Final mix
    pub final_mix_amount: f32,
    pub final_key_value: Vec3,
    pub final_key_threshold: f32,
    pub final_key_soft: f32,
    pub final_mix_type: i32,
    pub final_mix_overflow: i32,
    pub final_key_order: i32,
}

/// LFO (Low Frequency Oscillator) bank
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct LfoBank {
    /// LFO rate (-1 to 1, or BPM synced)
    pub rate: f32,
    /// LFO amplitude
    pub amplitude: f32,
    /// LFO waveform (0=sine, 1=triangle, 2=saw, 3=square, 4=random)
    pub waveform: i32,
    /// Whether LFO is tempo-synced
    pub tempo_sync: bool,
    /// Beat division for tempo sync
    pub division: i32,
    /// Current phase (0-1)
    pub phase: f32,
}

impl Default for Block1Params {
    fn default() -> Self {
        Self {
            ch1_x_displace: 0.0,
            ch1_y_displace: 0.0,
            ch1_z_displace: 1.0,
            ch1_rotate: 0.0,
            ch1_hsb_attenuate: Vec3::ONE,
            ch1_hsb_attenuate_x: 1.0,
            ch1_hsb_attenuate_y: 1.0,
            ch1_hsb_attenuate_z: 1.0,
            ch1_posterize: 16.0,
            ch1_kaleidoscope_amount: 0.0,
            ch1_kaleidoscope_slice: 0.0,
            ch1_blur_amount: 0.0,
            ch1_blur_radius: 1.0,
            ch1_sharpen_amount: 0.0,
            ch1_sharpen_radius: 1.0,
            ch1_filters_boost: 0.0,
            ch1_h_mirror: false,
            ch1_v_mirror: false,
            ch1_h_flip: false,
            ch1_v_flip: false,
            ch1_hue_invert: false,
            ch1_saturation_invert: false,
            ch1_bright_invert: false,
            ch1_rgb_invert: false,
            ch1_geo_overflow: 0,
            ch1_solarize: false,
            ch1_posterize_switch: false,
            ch1_hd_aspect_on: false,
            ch2_mix_amount: 0.0,
            ch2_key_value_red: 0.0,
            ch2_key_value_green: 0.0,
            ch2_key_value_blue: 0.0,
            ch2_key_threshold: 1.0,
            ch2_key_soft: 0.0,
            ch2_mix_type: 0,
            ch2_mix_overflow: 0,
            ch2_key_order: 0,
            ch2_key_mode: 0,
            ch2_x_displace: 0.0,
            ch2_y_displace: 0.0,
            ch2_z_displace: 1.0,
            ch2_rotate: 0.0,
            ch2_hsb_attenuate: Vec3::ONE,
            ch2_hsb_attenuate_x: 1.0,
            ch2_hsb_attenuate_y: 1.0,
            ch2_hsb_attenuate_z: 1.0,
            ch2_posterize: 16.0,
            ch2_kaleidoscope_amount: 0.0,
            ch2_kaleidoscope_slice: 0.0,
            ch2_blur_amount: 0.0,
            ch2_blur_radius: 1.0,
            ch2_sharpen_amount: 0.0,
            ch2_sharpen_radius: 1.0,
            ch2_filters_boost: 0.0,
            ch2_h_mirror: false,
            ch2_v_mirror: false,
            ch2_h_flip: false,
            ch2_v_flip: false,
            ch2_hue_invert: false,
            ch2_saturation_invert: false,
            ch2_bright_invert: false,
            ch2_rgb_invert: false,
            ch2_geo_overflow: 0,
            ch2_solarize: false,
            ch2_posterize_switch: false,
            ch2_hd_aspect_on: false,
            fb1_mix_amount: 0.0,
            fb1_key_value_red: 0.0,
            fb1_key_value_green: 0.0,
            fb1_key_value_blue: 0.0,
            fb1_key_threshold: 1.0,
            fb1_key_soft: 0.0,
            fb1_mix_type: 0,
            fb1_mix_overflow: 0,
            fb1_key_order: 0,
            fb1_key_mode: 0,
            fb1_x_displace: 0.0,
            fb1_y_displace: 0.0,
            fb1_z_displace: 1.0,
            fb1_rotate: 0.0,
            fb1_shear_matrix: Vec4::new(1.0, 0.0, 0.0, 1.0),
            fb1_shear_matrix_x: 1.0,
            fb1_shear_matrix_y: 0.0,
            fb1_shear_matrix_z: 0.0,
            fb1_shear_matrix_w: 1.0,
            fb1_kaleidoscope_amount: 0.0,
            fb1_kaleidoscope_slice: 0.0,
            fb1_h_mirror: false,
            fb1_v_mirror: false,
            fb1_h_flip: false,
            fb1_v_flip: false,
            fb1_rotate_mode: 0,
            fb1_geo_overflow: 0,
            fb1_hsb_offset: Vec3::ZERO,
            fb1_hsb_offset_x: 0.0,
            fb1_hsb_offset_y: 0.0,
            fb1_hsb_offset_z: 0.0,
            fb1_hsb_attenuate: Vec3::ONE,
            fb1_hsb_attenuate_x: 1.0,
            fb1_hsb_attenuate_y: 1.0,
            fb1_hsb_attenuate_z: 1.0,
            fb1_hsb_powmap: Vec3::ONE,
            fb1_hue_shaper: 1.0,
            fb1_posterize: 16.0,
            fb1_posterize_invert: 1.0 / 16.0,
            fb1_posterize_switch: false,
            fb1_hue_invert: false,
            fb1_saturation_invert: false,
            fb1_bright_invert: false,
            fb1_blur_amount: 0.0,
            fb1_blur_radius: 1.0,
            fb1_sharpen_amount: 0.0,
            fb1_sharpen_radius: 1.0,
            fb1_temporal_filter1_amount: 0.0,
            fb1_temporal_filter1_resonance: 0.0,
            fb1_temporal_filter2_amount: 0.0,
            fb1_temporal_filter2_resonance: 0.0,
            fb1_filters_boost: 0.0,
            fb1_delay_time: 1,
            fb1_delay_time_sync: false,
            fb1_delay_time_division: 2,  // Default to 1/4 beat
            ch1_input_select: 0,  // input1
            ch2_input_select: 1,  // input2
        }
    }
}

impl Default for Block2Params {
    fn default() -> Self {
        Self {
            block2_input_x_displace: 0.0,
            block2_input_y_displace: 0.0,
            block2_input_z_displace: 1.0,
            block2_input_rotate: 0.0,
            block2_input_hsb_attenuate: Vec3::ONE,
            block2_input_hsb_attenuate_x: 1.0,
            block2_input_hsb_attenuate_y: 1.0,
            block2_input_hsb_attenuate_z: 1.0,
            block2_input_posterize: 16.0,
            block2_input_kaleidoscope_amount: 0.0,
            block2_input_kaleidoscope_slice: 0.0,
            block2_input_blur_amount: 0.0,
            block2_input_blur_radius: 1.0,
            block2_input_sharpen_amount: 0.0,
            block2_input_sharpen_radius: 1.0,
            block2_input_filters_boost: 0.0,
            block2_input_h_mirror: false,
            block2_input_v_mirror: false,
            block2_input_h_flip: false,
            block2_input_v_flip: false,
            block2_input_hue_invert: false,
            block2_input_saturation_invert: false,
            block2_input_bright_invert: false,
            block2_input_rgb_invert: false,
            block2_input_geo_overflow: 0,
            block2_input_solarize: false,
            block2_input_posterize_switch: false,
            block2_input_hd_aspect_on: false,
            fb2_mix_amount: 0.0,
            fb2_key_value: Vec3::ZERO,
            fb2_key_threshold: 1.0,
            fb2_key_soft: 0.0,
            fb2_mix_type: 0,
            fb2_mix_overflow: 0,
            fb2_key_mode: 0,
            fb2_key_order: 0,
            fb2_x_displace: 0.0,
            fb2_y_displace: 0.0,
            fb2_z_displace: 1.0,
            fb2_rotate: 0.0,
            fb2_shear_matrix: Vec4::new(1.0, 0.0, 0.0, 1.0),
            fb2_shear_matrix_x: 1.0,
            fb2_shear_matrix_y: 0.0,
            fb2_shear_matrix_z: 0.0,
            fb2_shear_matrix_w: 1.0,
            fb2_kaleidoscope_amount: 0.0,
            fb2_kaleidoscope_slice: 0.0,
            fb2_h_mirror: false,
            fb2_v_mirror: false,
            fb2_h_flip: false,
            fb2_v_flip: false,
            fb2_rotate_mode: 0,
            fb2_geo_overflow: 0,
            fb2_hsb_offset: Vec3::ZERO,
            fb2_hsb_offset_x: 0.0,
            fb2_hsb_offset_y: 0.0,
            fb2_hsb_offset_z: 0.0,
            fb2_hsb_attenuate: Vec3::ONE,
            fb2_hsb_attenuate_x: 1.0,
            fb2_hsb_attenuate_y: 1.0,
            fb2_hsb_attenuate_z: 1.0,
            fb2_hsb_powmap: Vec3::ONE,
            fb2_hue_shaper: 1.0,
            fb2_posterize: 16.0,
            fb2_posterize_invert: 1.0 / 16.0,
            fb2_posterize_switch: false,
            fb2_hue_invert: false,
            fb2_saturation_invert: false,
            fb2_bright_invert: false,
            fb2_rgb_invert: false,
            fb2_blur_amount: 0.0,
            fb2_blur_radius: 1.0,
            fb2_sharpen_amount: 0.0,
            fb2_sharpen_radius: 1.0,
            fb2_temporal_filter1_amount: 0.0,
            fb2_temporal_filter1_resonance: 0.0,
            fb2_temporal_filter2_amount: 0.0,
            fb2_temporal_filter2_resonance: 0.0,
            fb2_filters_boost: 0.0,
            fb2_delay_time: 1,
            fb2_delay_time_sync: false,
            fb2_delay_time_division: 2,  // Default to 1/4 beat
            block2_input_select: 0,  // Default to block1
        }
    }
}

impl Default for Block3Params {
    fn default() -> Self {
        Self {
            block1_x_displace: 0.0,
            block1_y_displace: 0.0,
            block1_z_displace: 1.0,
            block1_rotate: 0.0,
            block1_shear_matrix: Vec4::new(1.0, 0.0, 0.0, 1.0),
            block1_shear_matrix_x: 1.0,
            block1_shear_matrix_y: 0.0,
            block1_shear_matrix_z: 0.0,
            block1_shear_matrix_w: 1.0,
            block1_kaleidoscope_amount: 0.0,
            block1_kaleidoscope_slice: 0.0,
            block1_h_mirror: false,
            block1_v_mirror: false,
            block1_rotate_mode: 0,
            block1_geo_overflow: 0,
            block1_h_flip: false,
            block1_v_flip: false,
            block1_colorize_switch: false,
            block1_colorize_hsb_rgb: 0,
            block1_colorize_band1: Vec3::ZERO,
            block1_colorize_band1_x: 0.0,
            block1_colorize_band1_y: 0.0,
            block1_colorize_band1_z: 0.0,
            block1_colorize_band2: Vec3::ZERO,
            block1_colorize_band2_x: 0.0,
            block1_colorize_band2_y: 0.0,
            block1_colorize_band2_z: 0.0,
            block1_colorize_band3: Vec3::ZERO,
            block1_colorize_band3_x: 0.0,
            block1_colorize_band3_y: 0.0,
            block1_colorize_band3_z: 0.0,
            block1_colorize_band4: Vec3::ZERO,
            block1_colorize_band4_x: 0.0,
            block1_colorize_band4_y: 0.0,
            block1_colorize_band4_z: 0.0,
            block1_colorize_band5: Vec3::ZERO,
            block1_colorize_band5_x: 0.0,
            block1_colorize_band5_y: 0.0,
            block1_colorize_band5_z: 0.0,
            block1_blur_amount: 0.0,
            block1_blur_radius: 1.0,
            block1_sharpen_amount: 0.0,
            block1_sharpen_radius: 1.0,
            block1_filters_boost: 0.0,
            block1_dither: 16.0,
            block1_dither_switch: false,
            block1_dither_type: 0,
            block2_x_displace: 0.0,
            block2_y_displace: 0.0,
            block2_z_displace: 1.0,
            block2_rotate: 0.0,
            block2_shear_matrix: Vec4::new(1.0, 0.0, 0.0, 1.0),
            block2_shear_matrix_x: 1.0,
            block2_shear_matrix_y: 0.0,
            block2_shear_matrix_z: 0.0,
            block2_shear_matrix_w: 1.0,
            block2_kaleidoscope_amount: 0.0,
            block2_kaleidoscope_slice: 0.0,
            block2_h_mirror: false,
            block2_v_mirror: false,
            block2_rotate_mode: 0,
            block2_geo_overflow: 0,
            block2_h_flip: false,
            block2_v_flip: false,
            block2_colorize_switch: false,
            block2_colorize_hsb_rgb: 0,
            block2_colorize_band1: Vec3::ZERO,
            block2_colorize_band1_x: 0.0,
            block2_colorize_band1_y: 0.0,
            block2_colorize_band1_z: 0.0,
            block2_colorize_band2: Vec3::ZERO,
            block2_colorize_band2_x: 0.0,
            block2_colorize_band2_y: 0.0,
            block2_colorize_band2_z: 0.0,
            block2_colorize_band3: Vec3::ZERO,
            block2_colorize_band3_x: 0.0,
            block2_colorize_band3_y: 0.0,
            block2_colorize_band3_z: 0.0,
            block2_colorize_band4: Vec3::ZERO,
            block2_colorize_band4_x: 0.0,
            block2_colorize_band4_y: 0.0,
            block2_colorize_band4_z: 0.0,
            block2_colorize_band5: Vec3::ZERO,
            block2_colorize_band5_x: 0.0,
            block2_colorize_band5_y: 0.0,
            block2_colorize_band5_z: 0.0,
            block2_blur_amount: 0.0,
            block2_blur_radius: 1.0,
            block2_sharpen_amount: 0.0,
            block2_sharpen_radius: 1.0,
            block2_filters_boost: 0.0,
            block2_dither: 16.0,
            block2_dither_switch: false,
            block2_dither_type: 0,
            matrix_mix_type: 0,
            matrix_mix_overflow: 0,
            bg_rgb_into_fg_red: Vec3::ZERO,
            bg_rgb_into_fg_green: Vec3::ZERO,
            bg_rgb_into_fg_blue: Vec3::ZERO,
            matrix_mix_r_to_r: 0.0,
            matrix_mix_r_to_g: 0.0,
            matrix_mix_r_to_b: 0.0,
            matrix_mix_g_to_r: 0.0,
            matrix_mix_g_to_g: 0.0,
            matrix_mix_g_to_b: 0.0,
            matrix_mix_b_to_r: 0.0,
            matrix_mix_b_to_g: 0.0,
            matrix_mix_b_to_b: 0.0,
            final_mix_amount: 0.0,
            final_key_value: Vec3::ZERO,
            final_key_threshold: 1.0,
            final_key_soft: 0.0,
            final_mix_type: 0,
            final_mix_overflow: 0,
            final_key_order: 0,
        }
    }
}

impl Default for LfoBank {
    fn default() -> Self {
        Self {
            rate: 0.15,
            amplitude: 1.0,
            waveform: 0,
            tempo_sync: false,
            division: 2,
            phase: 0.0,
        }
    }
}
